batch_size: 64
checkpoint_dir: ./checkpoints
dataset_path: /home/dpenmets/LIRA_work/robomimic_vd/robomimic/scripts/final_cfgs/demo_data_with_gaze/low_dim_gaze.hdf5
gradient_steps_per_epoch: 100
hidden_dim: 1024
input_dim: 64
learning_rate: 0.0001
log_frequency: 500
num_epochs: 2000
num_workers: 4
output_dim: 4
run_name: Feb_5_trial
wandb_entity: lira_pato
wandb_name: Feb_5_plain_exp
wandb_project: Feb_5
